apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "diskreport.fullname" . }}-cleaner
  labels:
    {{- include "diskreport.labels" . | nindent 4 }}
    diskreport.component: cleaner
spec:
  {{- if not .Values.cleaner.autoscaling.enabled }}
  replicas: {{ .Values.cleaner.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "diskreport.selectorLabels" . | nindent 6 }}
      diskreport.component: cleaner
  template:
    metadata:
      {{- with .Values.cleaner.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "diskreport.selectorLabels" . | nindent 8 }}
        diskreport.component: cleaner
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "diskreport.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.cleaner.podSecurityContext | nindent 8 }}
      containers:
        - name: cleaner
          securityContext:
            {{- toYaml .Values.cleaner.securityContext | nindent 12 }}
          image: "{{ .Values.cleaner.image.repository }}:{{ .Values.cleaner.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.cleaner.image.pullPolicy }}
          command:
            - /entrypoint-cleaner.sh
          env:
            - name: POSTGRES_HOST
              value: {{ .Release.Name }}-postgresql
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql.secretName" .Subcharts.postgresql }}
                  key: {{ include "postgresql.userPasswordKey" .Subcharts.postgresql }}
          resources:
            {{- toYaml .Values.cleaner.resources | nindent 12 }}
      {{- with .Values.cleaner.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cleaner.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cleaner.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
