apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-node
spec:
  schedule: "20 2 * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: demo-node
            image: node:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/bash
            - -c
            - |
              set -e
              export PRIV_64=LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBejFxaEhGYTcvSjJjYWNHQTArRm1LckpIbFBpZEJGQ0VjTEdqNytqeGwzU2s2dzcyCk93azZ0aTY3ckpuNWRQRDVFWmgwVUQvT0g0QzVMVWIvWGROODVBOGxhdmh6cTBURTdyLzUyZFJTUEkra0dER1AKTDFsN1NIR214RjgveEtFWVNId1hNZ2ZnMVNGeTJvWDhxcTZKUVZQZVp2dHlvUkRwaUVsckxET24wSWFTUER4dwpxeGs0MmdRc3k5bXVOcVMrSFk2NjM2NTVGRGlKUjlTeVF2eHZIbUtYcm92QjB6c0ZsbXViUjNHTkdNaThra3NUCm9iRkQzVmJ6VVFDM2dDMzdjK0RmbE1XYTRoNG9PcU1rVU40YlpCbTRCdk1WNURLSHVlQXR3L04zNHdBYVFZMm4KdGY2WEZvK2xsZnZnZ2xwcW4xRDVhMjVzMnVNeEhxN3pQR1BVaHdJREFRQUJBb0lCQUZKZW5EV1h0dUdvOHFPSQpQTmJ1YVJsNDdMcWU4RER3azB2NUpUaCtmc285aWUzZWFhNFdBbjZ3bmRqNDZZR3M0Q1EvUGFWTFUyUnNUQ05TCldzczQ0aG51Y2x6R0NaejFtbzJGTVlsNHNKcGlMVHQzSkh3WXZjS1BjMEg2M0dnTjNvbWMwZElNRXlKWFFUclIKa3dkeWdnK3pjMXZSY3ozTWJCaTVvWnRUZ2N4eGtjTXFzc1d2VHhEK2x5Y2V4OHlSVGUzV3N1QkgzbEhPSDY4SwpDRURISVdjTEtjL3V1bDNLVWpoN1RvQXZ4c1dZWEhtRkUyN1hESHBiOGRwSWRNQ3ZyVzI3emJHM1h1YjhHS1hlClZJVjhiOTRYRWUwN1JxbFVBMzhKY0F0L1NnSUZrQ1Y5d2x4c2FHYlA1RjVtMDlNSHVrLzJlZW1pOXRoVnZ3dEgKdnFKUlBRRUNnWUVBNktHMmRiTXNxN211RVBRZHVEcWQ2THh1TWNjT2ROL2NMMEVPMjdNUlA2RnNKbldhVUVUUApnOFlBUFlTNGdNbWVQN0hOZTVzY2JvTVBwZkpEQnZlT2dqV2t5eWxsMFlIbS8rbHZvbWZTT0lHUWFsd1lkYW9ZCldhemJSN1AyTndHUUkxK3U2LzZkTnRqTDVIZlVEU3c3d3Nwd3pQT3RsTXJaWDdSSGk5RUo1RWNDZ1lFQTVDN2kKTXBUdytBZnA4T25VQVFzanN2MnZ4NnBuK3Z2dTFWMG11UVBXOG1IZ1R4Y1NhK2dyNTd6NVNsWEVaK3dpTUJSKwpWUEdjcitURU9Pb2lmWWJvWUdQc1pYaGRBZTczSlhkRUh6U2RuejhPOVJZTGRZWmMxMjNLQzZ6cVlOMkNIWEFvCnBFcW42WEZ0Q0dMNkZDMjFsVjRlL1hHZzNJT2gvQXJ2UGZFZjdjRUNnWUJWam53VGg2VXJOeXY4a2p1SDhRNzQKZEt5MlkvWStKOExNSWtvN3BQejRBUDlNbWIzNlBZUndlMWJGU1ZXdUQvakNoanNEZGNXY0kxbVM5Nm1ORzJqdgpISm1TR3BTVzNBYkFJZk5yc0hGUlZOMXZNSlhTV0krQ0U1L0dIRHEyZWoydnROWVpkMWdNdnVrbUNxZ1RmQ3d5CmRNL05vT1U3THV1SlZqMWwvNmg2cXdLQmdRQ0ZtRFZ5NitUUk1zRHkvZFBUOEpPc0hmOG1aVXlQazZUWFlyeGoKSWk1Y3BwVlBlUENlSU1aajNTNFBLWHZlWkUvMzJtZkVqOWp1Mm45UDJ6VHFUV3dMMHpUNmk2ZllrL0k3QzBMbApDa2NtanlMUXQyRnFJNHFEenBHMm1EeDVEZmM2Q1FxaWRkc3RQKzFZTmFxNDJiSXdpM1NWYWt1R0Q4TnM3M0gyCjBBK2pnUUtCZ1FDeGJRQXp4YThRaUJtMWc0aDNmR3BxU0gvNmxqM3lqNTd6MDZWZXZQbENpcUhVQ2p3UFF1ZE4KWVlBVzk3cVlzV3laaTVoRFJlL2QzSHZ1UVoyU2drdzRXVHNwNkZGMXg3WkIvMStKWDdla3ZCNDFHS3RZOGZUaQpqVVQ1ZEtBejN3bE52OU9DMmtIc1kzaDZFMVI5T3dycFFBSEhFRXhmL0RpSFFyYXAzaVAyUmc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
              export REPORT_HOSTNAME=docker-node-latest-image
              export UPLOAD_SERVER=http://{{ include "diskreport.fullname" . }}-receiver
              export API_SERVER=http://{{ include "diskreport.fullname" . }}-frontend
              curl -# -o diskreport.sh ${API_SERVER}/diskreport.sh
              chmod +x diskreport.sh
              ./diskreport.sh 1
          restartPolicy: Never
