apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-debian
spec:
  schedule: "30 2 * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: demo-debian
            image: debian:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/bash
            - -c
            - |
              set -e
              export PRIV_64=LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBcG9vKytFQjAzdm53V1NDandXWTBGWWlFaVBqZlVjdm9hL0lSQS9TOUszRzBTaG5jCmhRYmJ6NWtoZDVwWTFTSkt0UHVlbXh6QWxkTE9KTUF1R3NYb3ZiYmlxV3ovTUpVd1Y4QUhzSmZFMDN0YXdSZ24KUFppWTFWTXpHWGZBaGZMSHEvQkVDWG5Kc3pTSk9PTzZTcFRrS2ZIWGhUaFZOdENRSmY3ckRGZ0pWRkVROFVsVgppTVRDOVgzVkNOQkFCdCtJdm9JZm1kOGM4VmVvejZGYURwMERTU0tsa3FHamFLUURxR1pZZCt0eG5SVnpaSmlICkpnQ3ZNejZlWWoySXBsVTh5QklXYXlQdEtJa0FOY0VCZnh1ZzJxWFhDVmlFRXZCWEhWMnRUM3krSzluNndNWjEKMWJtdUpMdnJVcVVHclNpelFENm9YYUNmbXlPdzBnZ01mTE40YVFJREFRQUJBb0lCQVFDQWh0ekdGbWliMU9TcQp4RWZjOEJWdU1PZW9GZm16Vk56UXdnWmp1VE50SGRsMy9yRnpjTEdmYTV5cWcxSGZXeEd3enllK3FkZnZTTHVUCkhVWDNuNWxaSUpXWkQrZDZCUWxFRDQxZnVpRkszVDVURzJMZFpMRStvWEVrVElrbVZ4SEdIaTFENnR2QkUrQjcKS1RVU2Jnb1FYUFpwZCtvNzNZWUI3TlJWdUhPcXY0NjhaOGZ0cVdXeGdBeW1LTUxmc3p2cGxwM21aNlRQQVNlZgpEaHhqcnZieXE2Y2JFd2FpbkkyRW15RE40bzJueW9vNkJaQzR5aFdPc1NaTWRHaEpaTDR2WVNBZmlGNlBFR0ZhCkpTWEZZRlJkNG5uNnA3MEJZNTNEK0REd2JsREU4OEppQnU1d1pnSGV2Qk5PaTBBMDU2djZ6OHZPNkV4Q0V5N1gKenpXRG05M3BBb0dCQU5NcE9MM2FSRXdKSXkyRjQ3amtzcm4rVlV3Qm9KQjB6dDc1QVBVNTVwcXNiaEdRaWMwVwo4QWhyYXYvY0p1VGNSbmZXbmxTSjg4aEtGeFJYQzZicXd2ZDBtVUpQbUpBeUQ5ZFRpREtJb01ZUkkvOCtRNmVNCndwUW9rNEROak5jV0N3SUJFWHJtRGIrV2xwajdjVTB4Q3JNY0FQVW1yT2lJU0NBc2lnWk5RNlBuQW9HQkFNbm4KYWI1dmF6Zzh1MXUvLzdTbmVVOFY3SmExdnJoRDJ5QWxWWVJhMnZyUjlaYk1abkdPam05RERXWDhaUlVUMjBCbwpnMlFDQm5PdjVUTEdpWWhyTGZsMnZuSmdoUllnQTJNSm01NklKaWd2dEZ0M25uUmt1cktyb1pZVHM1L1g1MThWClI2dUJMVktKUWJUTnY5cG5hcE9QWDZZK1dmT0pUS0pRNzAzQUtIY3ZBb0dBZHZxd0ZSRnFFQ25KMzNta2tXYVQKYWdkcmlsTVVaTERjYTNpRVdLaVNUaTdBS2pkMTNkQ0IyVXlsVXB0NmN0UEhCUGt4NTFKL3dTZzJEdWpwRU5rUQptQnZqeXlCTVIxdGQzNmNhZzliR09EUXFRMFNUSEZKTXhPeUVDRHhKa2x2Q1FoUFdCSmlod0lVYVFBTFZtWGY3Cm5tWTJCK3dOMjB3R3o5SW94MW83dFpzQ2dZQWhFemZQYXBFMTlUejhHc2ZZNEZhUERoaGoyQUlXVFlkb0RMV2wKcVB5V2VpNnhOV3JTejNlbDRtWWZmdWxRT3FDQVBKN0prMHRiU0VWVHZCSnJ0cU1oYXNKb0drZXpDQ3VGM2QwUQphMTFVMS92RHdDVEZESHRKS2JTZTBUdHJ4QUt6SU5sTXp5eU5pTTZxdjhuZURYTDRHVlNoOXpUbElHamRia1RGCmgrVVpJUUtCZ1FDU1FvVzR0OXRRTFlhZVB1N2VMVG1HVnhlaHhCZ2p4aDlwdWJiUTl3enpIQ2xRQmcrYmsrekwKS3pKSTVJeU04R2VsQTB3eElsSjdxOHZOTjZoV211QjJjWnMzek5nMzRZR2FkbUQrZDQ5UmJ2eXppRWhDcVQrKwp3M1Vab3d1ZnNjQVl4U1pab1hvVVpsUVJIM01uMEVWT3g4R3RsTVlUYitEUFFqcS8yQW1ZUFE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
              export REPORT_HOSTNAME=docker-debian-latest-image
              export UPLOAD_SERVER=http://{{ include "diskreport.fullname" . }}-receiver
              export API_SERVER=http://{{ include "diskreport.fullname" . }}-frontend
              apt-get update
              apt-get install -y curl
              curl -# -o diskreport.sh ${API_SERVER}/diskreport.sh
              chmod +x diskreport.sh
              ./diskreport.sh 1
          restartPolicy: Never
