apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-php
spec:
  schedule: "10 2 * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: demo-php
            image: php:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/bash
            - -c
            - |
              set -e
              export PRIV_64=LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBcncyYTJBbHJNaUhubEtaUXhpYTR5WDcrM3owN1c5dm1SN1JPL1M1NThmWTZXN0RZCnh4S05La25telhSUURrVVVlNHg4cisvNENSYjg2NmtQL0NKTmhQeVFObmxwK29EUWxQV2RxU3RBTGQ4eFAxMFcKWHc1aG9RdzhXSW5PM0VNTS8rLzZOZzlMcHdRTy9vcC9uTkFncmovcXJUS1U1Q1V6eTUxK0dOVGJWTVRidUw5Mgp5YW12TmFkL1F0VDZIMDBuVjhSL2wxd25KR0V6TWV6SUN2NDM0RW1nZnFtVTZNVTVpV1BmdWVEQ0pwUXo5cllHClRUQ2hNWDArcUpXNVFJZmYzc09idlNHZzhyUllIM2UrY09naDc2UkF2eGMrSGt3OUhReVZjNm55bEJRbTk4RVYKaDA2SC9RUUdaVnRQQndWRkZOOUxvaUxFdStsd3FKTWw4akk2b1FJREFRQUJBb0lCQUZUOExPV2ZSUHlVdTBKTwpzRDVUQkRsR3YyUVA3U1oranNEWEI5WWczekVhRW1EN2JYTFFUZHB2QUc5VWZaMC82bDdFNksvZHQ3UnFCYVkvCmNMUSt6eFcyTENsV0xwNWdOV05zRHZ2WE5KUlFuQzhmK1VGeTBQRUg2TEF2VDA5ZCtneXpLKzFjNWFTUzh0aWUKMHErRjE2ZmcvZ1RSM3JrWVdwb0t2dkk5UExKZEJtejhoSW9ycGh2OHp0T2hrVDlOV0Q1bFA2d1RJd0FwanRsWgplZkdrQjI2S3A4NnVlbmdIemNXanBBcVFUZHVjL0tKOFgwazdsa0kyQWpxckVtUFpTVmNIbkwyZ2s0a0MxOXhkCkFNTzVIRWg3SGlyOVZFU1VrdTE2Vm1ueGxta2lubXBQVDh2MFp1YW0ySlNRWTUvNE1CS0d4UmlBV1pNMzFHODYKeTVQQ1diRUNnWUVBM2RmRmgvOFg5emZSdVB4cjJvdE16bk1Tb01GWnJqM09KK093bU84RzZZOWQreng3WTV5SAo3UnB2T0prdm5SZnVoRXcvR1oySUlsRlNkM080WmdmT04yNk81TFZBa2QwZnhKNnhMZlROZmNiWkYyaHFyM1lwCjlTUTRxRi9TbklXZkpEV3Fta2JVWUEzdCt0Yi9GRGppVkFRcit6MjZoTmpvbkVEU2dsOWFWVDBDZ1lFQXlnR08KR0l0b0QrLzQ4ZlFNYVAyeWN3dURTcUpFYk1IQVY5Y01BSXZJSFkrS3VuOU52M0ZRTTBNTnBYWGxmeXhZcHRQYQphbFB0Tm5CanhjYmpwQWRBdmE5dWowSGxlWkdNNEk3YmRYZnQzNGkvUTZYdWEzcjNBVzZpcTFUTi9ldzBlQ0pMCjAxNmh6TU9kbEErN2ZDVGRzSFZDd3VxL2Q3elNWN2M2cXBYVU9UVUNnWUVBbmRYNjhIdUtiWllGWFB3Yk1HNlQKd3Y4VWJkT2pIdGxTYUFjVGludm1DeDY1MnhwNUg3SXE4NE12UnJHV3NzcG9KVENxWkdzMGhGWWZ1bVZXK1NEcwprM3ZScHQ5ZWhXa3lSUTR6T1dOSElRbnRRejVEU1h0azlzbENsbWsyeTY0MlArais3SzBnUlFja0hxZ0E3RDVjCnFUSWVxSzZPbWg1SndZSk5RL3picEhFQ2dZRUF0bEtHL1BJK0h6eFpkWS91NzRnald5REdCRVBHL0Y0M2kxQ20KSFl3TU4xb0tQVitQUGI0NVE3cytndHVSSXFKVTlXWDdHY0xjTkNsbWMraWFKNzhBR1BSUkZtM0VmMS8yUmV2SwplaENmbXdUaWxGMGNmdGZDUHdHclFuWk5ZZVNpU3RleGxub3dFUTl4bDJSSHRMblZlV0dzdXg2RFo3LytIWHRjCk1RRUFSZzBDZ1lFQWwraVBPeXVReUFvUUVnSTBwcXAzWVJBS01UZHNZSlBqRkYwQUxDai9OSVo4MlNUbnp6TUIKZVRQR2g5MUlheTZEK0F6TitxeERmdWZ2di9ySi85a0dqcU5LNUdFYW0xZzg4aWgyUXU2cXUvNGdXTUJuOWprQgpQTUJxWEJNTE8yUExRS3VNWDA1alVHR2tVZFhGNUNXREJiek5qeEpVTU0rTFhySHY1cGQ2cWR3PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
              export REPORT_HOSTNAME=docker-php-latest-image
              export UPLOAD_SERVER=http://{{ include "diskreport.fullname" . }}-receiver
              export API_SERVER=http://{{ include "diskreport.fullname" . }}-frontend
              curl -# -o diskreport.sh ${API_SERVER}/diskreport.sh
              chmod +x diskreport.sh
              ./diskreport.sh 1
          restartPolicy: Never
