apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "diskreport.fullname" . }}-importer
  labels:
    {{- include "diskreport.labels" . | nindent 4 }}
    diskreport.component: importer
spec:
  {{- if not .Values.importer.autoscaling.enabled }}
  replicas: {{ .Values.importer.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "diskreport.selectorLabels" . | nindent 6 }}
      diskreport.component: importer
  template:
    metadata:
      {{- with .Values.importer.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "diskreport.selectorLabels" . | nindent 8 }}
        diskreport.component: importer
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "diskreport.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.importer.podSecurityContext | nindent 8 }}
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: {{ include "diskreport.fullname" . }}-uploads
      containers:
        - name: importer
          securityContext:
            {{- toYaml .Values.importer.securityContext | nindent 12 }}
          image: "{{ .Values.importer.image.repository }}:{{ .Values.importer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.importer.image.pullPolicy }}
          env:
            - name: POSTGRES_HOST
              value: {{ .Release.Name }}-postgresql
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql.secretName" .Subcharts.postgresql }}
                  key: {{ include "postgresql.userPasswordKey" .Subcharts.postgresql }}
          volumeMounts:
            - name: uploads
              mountPath: /diskreport/new
          resources:
            {{- toYaml .Values.importer.resources | nindent 12 }}
      {{- with .Values.importer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.importer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.importer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
