apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "diskreport.fullname" . }}-receiver
  labels:
    {{- include "diskreport.labels" . | nindent 4 }}
    diskreport.component: receiver
spec:
  {{- if not .Values.receiver.autoscaling.enabled }}
  replicas: {{ .Values.receiver.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "diskreport.selectorLabels" . | nindent 6 }}
      diskreport.component: receiver
  template:
    metadata:
      {{- with .Values.receiver.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "diskreport.selectorLabels" . | nindent 8 }}
        diskreport.component: receiver
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "diskreport.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.receiver.podSecurityContext | nindent 8 }}
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: {{ include "diskreport.fullname" . }}-uploads
      containers:
        - name: receiver
          securityContext:
            {{- toYaml .Values.receiver.securityContext | nindent 12 }}
          image: "{{ .Values.receiver.image.repository }}:{{ .Values.receiver.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.receiver.image.pullPolicy }}
          volumeMounts:
            - name: uploads
              mountPath: /diskreport/new
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
          resources:
            {{- toYaml .Values.receiver.resources | nindent 12 }}
      {{- with .Values.receiver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.receiver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.receiver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
